services:
  tambolaapi:
    image: tambolaapi
    build: .
    env_file:
      - .env
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src/app
    command: go run . -b 0.0.0.0
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${{secrets.DB_USER}}
      - POSTGRES_PASSWORD=${{secrets.DB_PASSWORD}}
      - POSTGRES_DB=${{secrets.DB_NAME}}
      - POSTGRES_HOST=${{secrets.DB_HOST}}
      - POSTGRES_PORT=${{secrets.DB_PORT}}
      - POSTGRES_SSLMODE=${{secrets.DB_SSLMODE}}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
