services:
  tambolaapi:
    image: tambolaapi
    environment:
      POSTGRES_HOST: "db"
      POSTGRES_PORT: "5432"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "tambola"
      POSTGRES_SSLMODE: "disable"
    build: .
    # env_file:
    #   - .env
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src/app
    command: go run . -b 0.0.0.0
  db:
    image: postgres:alpine
    environment:
      POSTGRES_HOST: "db"
      POSTGRES_PORT: "5432"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "tambola"
      POSTGRES_SSLMODE: "disable"
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
