name: Docker Image CD

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull Docker image
        run: sudo docker pull m0hitkumar/tambola-api:latest
      - name: Delete Old docker container
        run: sudo docker rm -f tambola-api-container || true
      - name: Run Docker Container
        env:
          DB_HOST: ${{secrets.DB_HOST}}
          DB_PORT: ${{secrets.PORT}}
          DB_USER: ${{secrets.DB_USER}}
          DB_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
          DB_NAME: ${{secrets.DB_NAME}}
          DB_SSLMODE: ${{secrets.DB_SSLMODE}}
        run: sudo docker run -d -p 8080:8080  --name tambola-api-container -e ENV=production -e DB_HOST=$DB_HOST -e DB_PORT=$DB_PORT -e DB_USER=$DB_USER -e DB_PASSWORD=$DB_PASSWORD -e DB_NAME=$DB_NAME -e DB_SSLMODE=$DB_SSLMODE m0hitkumar/tambola-api
