name: Deploy Go Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Create .env file
        run: echo "PORT=${{ secrets.PORT }}" >> .env
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t m0hitkumar/tambola-api .
      - name: Push image to docker hub
        run: docker push m0hitkumar/tambola-api:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull docker image
        run: docker pull m0hitkumar/tambola-api:latest
      - name: Delete old container
        run: docker rm -f tambola-api-container
      - name: Run docker container
        run: docker run -d -p 4040:4040 --name tambola-api-container --env-file .env m0hitkumar/tambola-api
