name: Deploy Go Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t m0hitkumar/tambola-cicd .
      - name: Push image to docker hub
        run: docker push m0hitkumar/tambola-cicd:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull docker image
        run: sudo docker pull m0hitkumar/tambola-cicd:latest
      - name: Delete old container
        run: sudo docker rm -f tambola-cicd-container || true
      - name: Run docker container
        run: sudo docker run -d -p 8080:8080 --name tambola-api-container m0hitkumar/tambola-cicd
