name: Deploy Go Application

on:
  push:
    branches:
      - main
env:
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_PORT: ${{ secrets.DB_PORT }}
  DB_SSLMODE: ${{ secrets.DB_SSLMODE }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ env.DOCKER_USERNAME }} -p ${{ env.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t m0hitkumar/tambola-api .
      - name: Push image to docker hub
        run: docker push m0hitkumar/tambola-api:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull docker image
        run: docker pull m0hitkumar/tambola-api:latest
      - name: Delete old container
        run: docker rm -f tambola-api-container
      - name: Run docker container
        run: docker run -d -p 4040:4040 --name tambola-api-container m0hitkumar/tambola-api
